#!/usr/bin/env bash

if
  [[ -s "/home/vagrant/.rvm/gems/ruby-2.3.3@movie_store/environment" ]]
then
  source "/home/vagrant/.rvm/gems/ruby-2.3.3@movie_store/environment"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/vagrant/.rvm/gems/ruby-2.3.3@movie_store/environment'" >&2
  exit 1
fi
